//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Info
    {
        public int Sid { get; set; }
        public string Sname { get; set; }
        public string Degree { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
    }
}
